# Generated by Django 4.0.4 on 2022-05-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_price', models.IntegerField()),
                ('introduce', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_market.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_market.user')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_market.user'),
        ),
    ]
